export const allTypes = {
  NUMBER_INCREASE: "NUMBER_INCREASE",
  NUMBER_DECRES: "NUMBER_DECRES",
  // todo app

  ADD_INPUT_TEXT: "ADD_INPUT_TEXT",
  REMOVE_INPUT_TEXT: "REMOVE_INPUT_TEXT",
  DELET_ALL_LIST: "DELET_ALL_LIST",
};
